#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include <time.h>

#include "gba.h"
#include "images/title.h"
#include "images/sky.h"
#include "images/airplane.h"
#include "images/gameover.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not required to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  WELCOME,
  NEXTSTART,
  GENERATE,
  CITYGEN,
  NEXT,
  AIRPLANES,
  GAMEOVER,
  GAMEOVERNEXT,
  WIN1,
  PREPLAY,
};

int wins = 0;
int main(void) {
  Picture airplane1 = {50, 30, 20, 20, airplane};
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
  char *cities[3] = {"Atlanta", "Chicago", "NYC"};
  int random_index = 0;
  
  int firstDraw = 0;
  char numOfWins[100];
  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      
      case START:
      random_index = randint(0, 3);  // Generate a random index between 0 and num_cities-1
      random_index = random_index % 3;
      char *selected_city = cities[random_index];
      waitForVBlank();
      drawFullScreenImageDMA(title);
      state = WELCOME;
      airplane1.x = 50;
      airplane1.y = 30;

      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        state = START;
      }

      break;
      
      case WELCOME:
      drawString(80, 30, "Welcome to the Tour America Game!", RED);
      drawString(100, 20, "Click Enter to generate Destination!", RED);
      if (KEY_DOWN(BUTTON_START, currentButtons)) {
        state = NEXTSTART;
      }

      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        state = START;
      }

      break;

      case NEXTSTART:
      waitForVBlank();
      drawFullScreenImageDMA(sky);
      state = GENERATE;
      
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        state = START;
      }

      break;
      
      case GENERATE:
      waitForVBlank();
      drawString(80, 40, "Your randomly generated ", RED);
      drawString(90, 40, "destination is: ", RED);
      drawString(100, 40, selected_city, RED);
      drawString(110, 40, "Click enter to continue ", RED);
      state = CITYGEN;
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        state = START;
      }      
      break;

      case CITYGEN:
      waitForVBlank();
      if (KEY_DOWN(BUTTON_START, currentButtons)) {
        state = NEXT;
      }
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        state = START;
      }
      break;

      case NEXT:
      drawRectDMA(0, 0, 240, 160, BLACK);
      drawString(110, 10, "Fly to your destination to win! ", RED);
      drawString(120, 10, "Click down", RED);
      state = PREPLAY;
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        state = START;
      }      
      break;

      case PREPLAY:
      if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
        state = PLAY;
      }
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        state = START;
      }
      break;

      case PLAY:
      waitForVBlank();

      drawRectDMA(300, 200, 50, 10, BLACK);
      firstDraw = 1;
      state = AIRPLANES;
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        state = START;
      }
      break;

      case AIRPLANES:
      waitForVBlank();
      sprintf(numOfWins, "Score: %d", wins);
      drawString(20, 90, numOfWins, WHITE); 

      if (firstDraw) {
        drawRectDMA(0, 0, 240, 160, BLACK);

        drawRectDMA(300, 200, 50, 10, BLACK);
        drawString(300, 200, "Atlanta", RED);

        drawRectDMA(340, 200, 50, 10, BLACK);
        drawString(340, 200, "Chicago", RED);

        drawRectDMA(380, 200, 50, 10, BLACK);
        drawString(380, 200, "NYC", RED);
        firstDraw = 0;
      }

      drawImageDMA(airplane1.x, airplane1.y, 20, 20, airplane);
      
      // collisions
      if (airplane1.x <= 0 || airplane1.x >= 150 || airplane1.y <= 0 || airplane1.y >= 230) {
        state = GAMEOVER;

      }
      

      if (airplane1.x >= 13 && airplane1.x <= 43 && airplane1.y >= 182 && airplane1.y <= 192) {
        airplane1.x = 50;
        airplane1.y = 30;
        state = (random_index == 0) ? WIN : GAMEOVER;

      }

      
      if (airplane1.x >= 58 && airplane1.x <= 83 && airplane1.y >= 182 && airplane1.y <= 192) {
        airplane1.x = 50;
        airplane1.y = 30;
        state = (random_index == 1) ? WIN : GAMEOVER;

      }

      if (airplane1.x >= 93 && airplane1.x <= 133 && airplane1.y >= 182 && airplane1.y <= 192) {
        airplane1.x = 50;
        airplane1.y = 30;
        state = (random_index == 2) ? WIN : GAMEOVER;

      }

      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        state = START;
      }
      if (KEY_DOWN(BUTTON_LEFT, BUTTONS)) {
        drawRectDMA(airplane1.x, airplane1.y, 20, 20, BLACK);
        airplane1.y -=2;
        drawImageDMA(airplane1.x, airplane1.y, 20, 20, airplane);
      }
      if (KEY_DOWN(BUTTON_RIGHT, BUTTONS)) { 
        drawRectDMA(airplane1.x, airplane1.y, 20, 20, BLACK);
        airplane1.y +=2;
        drawImageDMA(airplane1.x, airplane1.y, 20, 20, airplane);
      }
      if (KEY_DOWN(BUTTON_DOWN, BUTTONS)) { 
        drawRectDMA(airplane1.x, airplane1.y, 20, 20, BLACK);
        airplane1.x +=2;
        drawImageDMA(airplane1.x, airplane1.y, 20, 20, airplane);

      }
      if (KEY_DOWN(BUTTON_UP, BUTTONS)) { 
        drawRectDMA(airplane1.x, airplane1.y, 20, 20, BLACK);
        airplane1.x -=2;
        drawImageDMA(airplane1.x, airplane1.y, 20, 20, airplane);

      }

      break;

      case GAMEOVER:
      wins--;
      waitForVBlank();
      drawFullScreenImageDMA(gameover);
      state = GAMEOVERNEXT;
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        state = START;
      }
      break;

      case GAMEOVERNEXT:
      waitForVBlank();
      drawString(100, 100, "CLICK DOWN TO RESTART", RED);
      if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
        state = START;
      }
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        state = START;
      }
      break;

      case WIN:
      wins++;
      drawRectDMA(0, 0, 240, 160, WHITE);

      state = WIN1;
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        state = START;
      }
      break;

      case WIN1:
      drawString(80, 40, "You Won! ", RED);
      drawString(90, 40, "Click Down to Restart", RED);
      if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
        state = START;
      }
      if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
        state = START;
      }
      break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
